#!/bin/bash

# Backup script for data volumes of the api-vmware container.
# Should be placed in /etc/cron.weekly

PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin


now=`date +%Y%m%d-%H.%M`
api="api-f5"

# Name of the container volumes that shoul be backupped.
vols=(api-f5 api-f5-cacerts)

# Number of days of retention: delete backups older than this number of days.
retention=120

bckDir="/home/bck/${api}/volumes"
containerVolDir="/var/lib/containers/storage/volumes"


cd $containerVolDir || exit 1

for vol in ${vols[@]}; do
    bckFile="${vol}_${now}.tar.xz"

    tar cfJp ${bckDir}/$bckFile $vol && chmod 400 ${bckDir}/${bckFile}
done

# The backup script should run once a week.
# Delete backups older than 120 days.
for vol in $vols; do
    find $bckDir -name "${vol}_*" -mtime +${retention} -exec rm -f {} \;
done

