from rest_framework import serializers


class F5ProfilesSerializer(serializers.Serializer):
    class F5ProfilesInnerSerializer(serializers.Serializer):
        class F5ProfilesItemsSerializer(serializers.Serializer):
            class F5ProfilesReferenceSerializer(serializers.Serializer):
                link = serializers.CharField(max_length=255, required=True)

            name = serializers.CharField(max_length=255, required=True)
            partition = serializers.CharField(max_length=255, required=True)
            fullPath = serializers.CharField(max_length=255, required=True)
            generation = serializers.IntegerField(required=True)
            selfLink = serializers.CharField(max_length=255, required=True)
            defaultsFrom = serializers.CharField(max_length=255, required=True)
            defaultsFromReference = F5ProfilesReferenceSerializer(required=False)
            clientTimeout = serializers.IntegerField(required=True)
            ipTtlV4 = serializers.IntegerField(required=True)
            ipTtlV6 = serializers.IntegerField(required=True)
            mssOverride = serializers.IntegerField(required=True)
            otherPvaClientpktsThreshold = serializers.IntegerField(required=True)
            otherPvaServerpktsThreshold = serializers.IntegerField(required=True)
            pvaDynamicClientPackets = serializers.IntegerField(required=True)
            pvaDynamicServerPackets = serializers.IntegerField(required=True)
            receiveWindowSize = serializers.IntegerField(required=True)
            synCookieMss = serializers.IntegerField(required=True)
            tcpTimeWaitTimeout = serializers.IntegerField(required=True)
            appService = serializers.CharField(max_length=255, required=True)
            description = serializers.CharField(max_length=255, required=True)
            explicitFlowMigration = serializers.CharField(max_length=255, required=True)
            hardwareSynCookie = serializers.CharField(max_length=255, required=True)
            idleTimeout = serializers.CharField(max_length=255, required=True)
            ipDfMode = serializers.CharField(max_length=255, required=True)
            ipTosToClient = serializers.CharField(max_length=255, required=True)
            ipTosToServer = serializers.CharField(max_length=255, required=True)
            ipTtlMode = serializers.CharField(max_length=255, required=True)
            keepAliveInterval = serializers.CharField(max_length=255, required=True)
            lateBinding = serializers.CharField(max_length=255, required=True)
            linkQosToClient = serializers.CharField(max_length=255, required=True)
            linkQosToServer = serializers.CharField(max_length=255, required=True)
            looseClose = serializers.CharField(max_length=255, required=True)
            looseInitialization = serializers.CharField(max_length=255, required=True)
            otherPvaOffloadDirection = serializers.CharField(max_length=255, required=True)
            otherPvaWhentoOffload = serializers.CharField(max_length=255, required=True)
            priorityToClient = serializers.CharField(max_length=255, required=True)
            priorityToServer = serializers.CharField(max_length=255, required=True)
            pvaAcceleration = serializers.CharField(max_length=255, required=True)
            pvaFlowAging = serializers.CharField(max_length=255, required=True)
            pvaFlowEvict = serializers.CharField(max_length=255, required=True)
            pvaOffloadDynamic = serializers.CharField(max_length=255, required=True)
            pvaOffloadState = serializers.CharField(max_length=255, required=True)
            reassembleFragments = serializers.CharField(max_length=255, required=True)
            resetOnTimeout = serializers.CharField(max_length=255, required=True)
            rttFromClient = serializers.CharField(max_length=255, required=True)
            rttFromServer = serializers.CharField(max_length=255, required=True)
            serverSack = serializers.CharField(max_length=255, required=True)
            serverTimestamp = serializers.CharField(max_length=255, required=True)
            softwareSynCookie = serializers.CharField(max_length=255, required=True)
            synCookieEnable = serializers.CharField(max_length=255, required=True)
            synCookieWhitelist = serializers.CharField(max_length=255, required=True)
            tcpCloseTimeout = serializers.CharField(max_length=255, required=True)
            tcpGenerateIsn = serializers.CharField(max_length=255, required=True)
            tcpHandshakeTimeout = serializers.CharField(max_length=255, required=True)
            tcpPvaWhentoOffload = serializers.CharField(max_length=255, required=True)
            tcpStripSack = serializers.CharField(max_length=255, required=True)
            tcpWscaleMode = serializers.CharField(max_length=255, required=True)
            tcpTimestampMode = serializers.CharField(max_length=255, required=True)
            timeoutRecovery = serializers.CharField(max_length=255, required=True)

        items = F5ProfilesItemsSerializer(many=True)

    data = F5ProfilesInnerSerializer(required=True)
