#!/bin/bash

# Use image label to cleanup possible orphaned images.
oImgs=$(buildah images | grep -F '<none>' | awk '{print $3}')
for img in $oImgs ; do
    if buildah inspect $img | grep -q '"AUTOMATION_CONTAINER_IMAGE": "api-f5"'; then
        buildah rmi --force $img
    fi
done

if [ "$1" == "purge" ]; then
    if podman volume ls | awk '{print $2}' | grep -q ^api-f5$; then
        printf "\n* Clean up api-f5 volume...\n"
        podman volume rm -f api-f5
        podman volume rm -f api-f5-db
        podman volume rm -f api-f5-cacerts
    fi
fi

# De-schedule db backups.
(crontab -l | sed '/bck-db_api-f5.sh/d') | crontab -

# Force debconf cleanup.
echo PURGE | debconf-communicate automation-interface-api-f5-container

exit 0
