#!/bin/bash

printf "\n* Container prerm...\n"
printf "\n* Cleanup...\n"

if podman ps | awk '{print $2}' | grep -Eq '\blocalhost/api-f5(:|$)'; then
    podman stop -t 15 api-f5 &
    wait $! # Wait for the shutdown process of the container.
fi

if podman images | awk '{print $1}' | grep -q ^localhost/api-f5$; then
    buildah rmi --force api-f5
fi

# Be sure there is not rubbish around.
if podman ps --all | awk '{print $2}' | grep -E '\blocalhost/api-f5(:|$)'; then
    cIds=$( podman ps --all | awk '$2 ~ /^localhost\/api-f5(:|$)/ { print $1 }' )
    for id in $cIds; do
        podman rm -f $id
    done
fi

exit 0

