#!/bin/bash

printf "\n* Container prerm...\n"
printf "\n* Cleanup...\n"

if podman ps | awk '{print $2}' | grep -E '\blocalhost/api-f5(:|\b)'; then
    podman stop api-f5
fi

if podman images | awk '{print $1}' | grep -q ^localhost/api-f5$; then
    buildah rmi --force api-f5
fi

# Be sure there is not rubbish around.
if podman ps --all | awk '{print $2}' | grep -E '\blocalhost/api-f5(:|\b)'; then
    cIds=$( podman ps --all | awk '$2 ~ /^localhost\/api-f5/ { print $1 }' )
    for id in $cIds; do
        podman rm -f $id
    done
fi

exit 0

